development:
  adapter: postgresql
  encoding: unicode
  database: mydb_as_postgres
  pool: 5
  username: Sozdik
  password: Sozdik1992

test:
  adapter: postgresql
  encoding: unicode
  database: mydb_as_postgres
  pool: 5
  username: Sozdik
  password: Sozdik1992
